# Generated by Django 4.0.5 on 2022-06-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogRegApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fName',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lName',
            new_name='lname',
        ),
    ]
